// Code generated by mockery v2.50.0. DO NOT EDIT.

package _mock

import (
	context "context"
	component "simple-reconciliation-service/internal/app/component"

	embed "embed"

	errgroup "golang.org/x/sync/errgroup"

	mock "github.com/stretchr/testify/mock"

	repository "simple-reconciliation-service/internal/app/repository"

	server "simple-reconciliation-service/internal/app/server"

	service "simple-reconciliation-service/internal/app/service"
)

// IAppContext is an autogenerated mock type for the IAppContext type
type IAppContext struct {
	mock.Mock
}

// AddToEg provides a mock function with given fields: in
func (_m *IAppContext) AddToEg(in func()) {
	_m.Called(in)
}

// GetComponents provides a mock function with no fields
func (_m *IAppContext) GetComponents() *component.Components {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetComponents")
	}

	var r0 *component.Components
	if rf, ok := ret.Get(0).(func() *component.Components); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*component.Components)
		}
	}

	return r0
}

// GetCtx provides a mock function with no fields
func (_m *IAppContext) GetCtx() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCtx")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// GetCtxCancel provides a mock function with no fields
func (_m *IAppContext) GetCtxCancel() context.CancelFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCtxCancel")
	}

	var r0 context.CancelFunc
	if rf, ok := ret.Get(0).(func() context.CancelFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.CancelFunc)
		}
	}

	return r0
}

// GetEg provides a mock function with no fields
func (_m *IAppContext) GetEg() *errgroup.Group {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEg")
	}

	var r0 *errgroup.Group
	if rf, ok := ret.Get(0).(func() *errgroup.Group); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errgroup.Group)
		}
	}

	return r0
}

// GetEmbedFS provides a mock function with no fields
func (_m *IAppContext) GetEmbedFS() *embed.FS {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmbedFS")
	}

	var r0 *embed.FS
	if rf, ok := ret.Get(0).(func() *embed.FS); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*embed.FS)
		}
	}

	return r0
}

// GetRepositories provides a mock function with no fields
func (_m *IAppContext) GetRepositories() *repository.Repositories {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepositories")
	}

	var r0 *repository.Repositories
	if rf, ok := ret.Get(0).(func() *repository.Repositories); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Repositories)
		}
	}

	return r0
}

// GetServers provides a mock function with no fields
func (_m *IAppContext) GetServers() *server.Server {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServers")
	}

	var r0 *server.Server
	if rf, ok := ret.Get(0).(func() *server.Server); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*server.Server)
		}
	}

	return r0
}

// GetServices provides a mock function with no fields
func (_m *IAppContext) GetServices() *service.Services {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServices")
	}

	var r0 *service.Services
	if rf, ok := ret.Get(0).(func() *service.Services); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Services)
		}
	}

	return r0
}

// Shutdown provides a mock function with no fields
func (_m *IAppContext) Shutdown() {
	_m.Called()
}

// Start provides a mock function with no fields
func (_m *IAppContext) Start() {
	_m.Called()
}

// NewIAppContext creates a new instance of IAppContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAppContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAppContext {
	mock := &IAppContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
