// Code generated by mockery v2.53.3. DO NOT EDIT.

package _mock

import (
	systems "simple-reconciliation-service/internal/pkg/reconcile/parser/systems"

	mock "github.com/stretchr/testify/mock"
)

// SystemTrxDataInterface is an autogenerated mock type for the SystemTrxDataInterface type
type SystemTrxDataInterface struct {
	mock.Mock
}

// GetAmount provides a mock function with no fields
func (_m *SystemTrxDataInterface) GetAmount() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAmount")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// GetTransactionTime provides a mock function with no fields
func (_m *SystemTrxDataInterface) GetTransactionTime() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionTime")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTrxID provides a mock function with no fields
func (_m *SystemTrxDataInterface) GetTrxID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTrxID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetType provides a mock function with no fields
func (_m *SystemTrxDataInterface) GetType() systems.TrxType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 systems.TrxType
	if rf, ok := ret.Get(0).(func() systems.TrxType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(systems.TrxType)
	}

	return r0
}

// ToSystemTrxData provides a mock function with no fields
func (_m *SystemTrxDataInterface) ToSystemTrxData() (*systems.SystemTrxData, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToSystemTrxData")
	}

	var r0 *systems.SystemTrxData
	var r1 error
	if rf, ok := ret.Get(0).(func() (*systems.SystemTrxData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *systems.SystemTrxData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*systems.SystemTrxData)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSystemTrxDataInterface creates a new instance of SystemTrxDataInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSystemTrxDataInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SystemTrxDataInterface {
	mock := &SystemTrxDataInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
