[sqlite]
is_enabled = true
is_do_logging = false

[sqlite.write]
is_enabled = true
#db_path = ":memory:"
db_path = "./reconciliation.db"
cache = "shared"
journal_mode = "WAL"

[sqlite.read]
is_enabled = true
db_path = ":memory:"
#db_path = "./sample.db"
cache = "shared"
journal_mode = "WAL"
